"""Conversation embedding — event-as-token for linguistic state control.

Follows the same additive embedding pattern as RoboticsEmbedding:
  h = ContentProjection(content_embedding) + MetadataProjection(metadata)
      + TypeEmbed(event_type) + PosEmbed(position)
      → LayerNorm → Dropout

Content embedding is generated by a LOCAL model (sentence-transformers).
Conversation data never leaves the device.
"""

import torch
import torch.nn as nn


class ConversationEmbedding(nn.Module):
    def __init__(
        self,
        d_model: int = 768,
        content_embed_dim: int = 384,
        n_metadata_features: int = 8,
        n_event_types: int = 8,
        max_events: int = 128,
        dropout: float = 0.1,
    ):
        super().__init__()
        self.d_model = d_model

        self.content_proj = nn.Sequential(
            nn.Linear(content_embed_dim, d_model),
            nn.GELU(),
            nn.Linear(d_model, d_model),
        )

        self.metadata_proj = nn.Sequential(
            nn.Linear(n_metadata_features, d_model // 4),
            nn.GELU(),
            nn.Linear(d_model // 4, d_model),
        )

        self.type_embed = nn.Embedding(n_event_types, d_model)
        self.pos_embed = nn.Embedding(max_events, d_model)

        self.norm = nn.LayerNorm(d_model)
        self.dropout_layer = nn.Dropout(dropout)

    def forward(
        self,
        content_embeddings: torch.Tensor,
        metadata_features: torch.Tensor,
        event_types: torch.Tensor,
        positions: torch.Tensor,
    ) -> torch.Tensor:
        h = (self.content_proj(content_embeddings)
             + self.metadata_proj(metadata_features)
             + self.type_embed(event_types)
             + self.pos_embed(positions))
        return self.dropout_layer(self.norm(h))
